/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request OTP
         * @description Sends a 6-digit OTP via WhatsApp (primary) with SMS fallback. Story 1.1.
         */
        post: operations["AuthController_requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify OTP
         * @description Returns access + refresh JWT on success. Creates the user on first verify.
         */
        post: operations["AuthController_verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token
         * @description Story 1.2 — returns a new access + refresh pair. Old refresh becomes invalid (rotation). Replaying an already-rotated refresh revokes the entire family. Error codes (body.code on 401): refresh_invalid_or_expired, refresh_reuse_detected, user_suspended.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user profile */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own profile (Story 1.8)
         * @description Self-update for any authenticated user. Today: displayName only. Vendor-specific fields → PATCH /vendors/me; rider-specific → PATCH /riders/me. MoMo number change with OTP-on-new-number confirmation is deferred — admin oversight covers MVP.
         */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/api/users/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved addresses (Story 3.2) */
        get: operations["AddressesController_list"];
        put?: never;
        /**
         * Save a new address (max 3 per user)
         * @description Conflict code: address_limit_reached. Setting isDefault demotes any existing default.
         */
        post: operations["AddressesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace an address (ownership-checked) */
        put: operations["AddressesController_update"];
        post?: never;
        /** Delete an address */
        delete: operations["AddressesController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own orders (recent first, max 30) */
        get: operations["OrdersController_listMine"];
        put?: never;
        /**
         * Create order from cart (Story 3.1)
         * @description Validates cart against vendor + items + stock, computes fee/total server-side, enforces minimum order. Idempotent via `Idempotency-Key` header (Story 3.14): a retried request with the same key returns the original order. Error codes: vendor_not_found, vendor_closed, item_not_in_vendor_menu, item_out_of_stock, order_below_minimum.
         */
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Order detail
         * @description Visible to the consumer who placed it AND to the target vendor.
         */
        get: operations["OrdersController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Consumer cancel — only before vendor acceptance (Story 3.8)
         * @description Cash orders cancel cleanly. MoMo orders enter cancelled state immediately; the refund is processed asynchronously by the payments module.
         */
        patch: operations["OrdersController_cancel"];
        trace?: never;
    };
    "/api/orders/{orderId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate vendor + rider post-delivery (Story 3.9)
         * @description Both scores required. 24h window from deliveredAt. One rating per order. Error codes: order_not_rateable, order_already_rated, rating_window_expired.
         */
        post: operations["OrdersController_rate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/vendor/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vendor inbox — list own orders (Story 3.7)
         * @description Optional `status` query filters to a single state — pass `CONFIRMED` for "awaiting decision".
         */
        get: operations["OrdersController_vendorList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Vendor accepts an order (Story 3.7) */
        patch: operations["OrdersController_accept"];
        trace?: never;
    };
    "/api/orders/{orderId}/refuse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Vendor refuses with reason (Story 3.7)
         * @description POWER_OUTAGE is non-penalising; everything else counts toward the weekly refusal alert.
         */
        patch: operations["OrdersController_refuse"];
        trace?: never;
    };
    "/api/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an informal vendor application
         * @description Story 2.0 — single-shot submission for the 5-screen onboarding form. Creates User + Vendor + first Item atomically (Vendor.status = PENDING_REVIEW). Photos uploaded to R2. WhatsApp confirmation fires after commit (fire-and-forget). Conflict codes: vendor_already_submitted, phone_used_by_other_role.
         */
        post: operations["VendorController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own vendor profile (Story 1.8)
         * @description Vendor-self-update for name, description, and momoPhone. Photo is a separate multipart endpoint (PATCH /vendors/me/photo). Quartier / landmark moves and commission edits stay admin-only.
         */
        patch: operations["VendorController_updateMe"];
        trace?: never;
    };
    "/api/vendors/me/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Replace own profile photo (Story 1.8)
         * @description Multipart field `photo`. Same size + MIME guardrails as onboarding.
         */
        patch: operations["VendorController_updateMePhoto"];
        trace?: never;
    };
    "/api/vendors/me/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own menu items (Story 2.2 / 2.3) */
        get: operations["MenuController_listItems"];
        put?: never;
        /**
         * Create a menu item (Story 2.2 / 2.3)
         * @description Informal vendors capped at 15 items / 2 categories. Restaurants unlimited. Conflict codes: menu_limit_reached, category_not_yours, category_not_found.
         */
        post: operations["MenuController_createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/me/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a menu item */
        put: operations["MenuController_updateItem"];
        post?: never;
        /** Delete a menu item */
        delete: operations["MenuController_deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/me/items/{itemId}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 1-tap stock toggle (Story 2.10)
         * @description Lightweight endpoint specifically for the dashboard "Disponible / Épuisé" switch. Designed to take a Tecno/Itel 1-tap on 3G without blocking on payload size.
         */
        patch: operations["MenuController_setStock"];
        trace?: never;
    };
    "/api/vendors/me/items/{itemId}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Upload / replace an item photo */
        patch: operations["MenuController_setPhoto"];
        trace?: never;
    };
    "/api/vendors/me/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own menu categories */
        get: operations["MenuController_listCategories"];
        put?: never;
        /**
         * Create a menu category (Story 2.3)
         * @description Informal vendors capped at 2 categories. Conflict codes: category_limit_reached, category_name_taken.
         */
        post: operations["MenuController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/me/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category. Items in it are detached (categoryId = NULL). */
        delete: operations["MenuController_deleteCategory"];
        options?: never;
        head?: never;
        /** Rename / reorder a category */
        patch: operations["MenuController_updateCategory"];
        trace?: never;
    };
    "/api/vendors/me/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read own availability + hours (Story 2.4)
         * @description Returns { isOpen, hours, isOpenNow }. `isOpenNow` is a server-computed live flag; the dashboard renders straight from it without having to reimplement weekday/clock math.
         */
        get: operations["AvailabilityController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle Ouvert / Fermé (Story 2.4 — 1-tap)
         * @description INFORMAL: this is the only availability signal. RESTAURANT: same toggle today; the future hours-cron will flip it automatically based on configured hours.
         */
        patch: operations["AvailabilityController_setAvailability"];
        trace?: never;
    };
    "/api/vendors/me/hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace weekly opening hours (Story 2.4 — restaurant)
         * @description Days absent from the body = closed that day. Times in 24h "HH:MM". INFORMAL vendors can call this too — it just won't affect isOpenNow.
         */
        put: operations["AvailabilityController_setHours"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse vendors near a location (Story 2.5)
         * @description Returns ACTIVE + isOpen vendors within radius (default 10km) ranked by distance. Each card carries server-computed distanceKm, deliveryFeeXAF, etaMinutes, and a plan tier (1 = ≤2km, 2 = ≤5km, 3 = >5km) so the consumer PWA can render the three sections without reimplementing geo math.
         */
        get: operations["BrowseController_catalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/{vendorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vendor public profile + menu (Story 2.6)
         * @description Returns vendor header, categories, and in-stock items. 404 if vendor is not ACTIVE.
         */
        get: operations["BrowseController_vendorPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/riders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a rider KYC application
         * @description Story 1.4 — single-shot multipart submission. Creates (or upgrades) the User and creates/updates the Rider row in PENDING_REVIEW. Files: idCardPhoto + selfiePhoto (always required), vehiclePhoto (required for MOTO/BICYCLE/CAR). licensePlate required for MOTO and CAR. Conflict codes: rider_already_active, phone_used_by_other_role, license_plate_already_used.
         */
        post: operations["RidersController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/riders/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own rider profile (Story 1.8)
         * @description Rider-self-update for preferredZone and momoPhone. vehicleType, photos, and licensePlate changes trigger admin re-validation and live in Story 6.2.
         */
        patch: operations["RidersController_updateMe"];
        trace?: never;
    };
    "/api/riders/me/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle online / offline (Story 4.1)
         * @description 1-tap "Je commence" / "Pause". Account must be ACTIVE — riders in PENDING_REVIEW or CORRECTION_REQUESTED cannot go online.
         */
        patch: operations["RidersController_setAvailability"];
        trace?: never;
    };
    "/api/riders/me/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push 15s GPS heartbeat (Story 4.4)
         * @description Updates lastLocation + lastSeenAt. Implicit online — keeps dispatch eligible through brief network blips. Rider is dropped from dispatch once lastSeenAt > 60s.
         */
        post: operations["RidersController_pushHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/riders/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assigned + in-flight courses (Story 4.2) */
        get: operations["RidersController_listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/riders/me/courses/{orderId}/picked-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rider confirms pickup at vendor (Story 4.2)
         * @description Transitions ACCEPTED / IN_PREP / READY_PICKUP → PICKED_UP.
         */
        patch: operations["RidersController_markPickedUp"];
        trace?: never;
    };
    "/api/riders/me/courses/{orderId}/delivered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rider confirms drop-off (Story 4.2)
         * @description Transitions PICKED_UP → DELIVERED. Delivery proof photo (Story 4.10) lands later.
         */
        patch: operations["RidersController_markDelivered"];
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login (email + password)
         * @description Story 1.6 — issues an 8h access JWT for ADMIN/SUPER_ADMIN/OPERATOR/VIEWER users. No refresh-token flow (admin re-enters password at end of session). Lockout: 5 failed attempts in 15 min → account_locked; super-admin must unlock. Error codes (body.code on 401): invalid_credentials, account_locked.
         */
        post: operations["AdminAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/vendors/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vendors awaiting approval (Story 6.2) */
        get: operations["AdminValidationController_listPendingVendors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/vendors/{vendorId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a vendor application
         * @description Flips Vendor.status to ACTIVE + sets validatedAt. Fires the "🎉 en ligne" WhatsApp.
         */
        post: operations["AdminValidationController_approveVendor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/vendors/{vendorId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a vendor application
         * @description Sets REJECTED + rejectionReason. Fires WhatsApp with the reason.
         */
        post: operations["AdminValidationController_rejectVendor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/vendors/{vendorId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a vendor (Stories 1.7 + 6.2)
         * @description Flips status to SUSPENDED, forces isOpen=false, and revokes the vendor's JWTs via the Redis blacklist (Story 1.7) — their tokens stop working on the very next request.
         */
        post: operations["AdminValidationController_suspendVendor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/vendors/{vendorId}/unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lift a vendor suspension — clears the JWT blacklist. */
        post: operations["AdminValidationController_unsuspendVendor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/riders/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List riders awaiting KYC approval */
        get: operations["AdminValidationController_listPendingRiders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/riders/{riderId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a rider KYC */
        post: operations["AdminValidationController_approveRider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/riders/{riderId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a rider application */
        post: operations["AdminValidationController_rejectRider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/riders/{riderId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a rider (revokes JWTs immediately) */
        post: operations["AdminValidationController_suspendRider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/riders/{riderId}/unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lift a rider suspension */
        post: operations["AdminValidationController_unsuspendRider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/pay/momo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate a Campay MoMo collect (Stories 3.3, 3.4)
         * @description Triggers the Campay USSD prompt on the payer phone. Returns immediately with a reference; the order flips to CONFIRMED + PAID once Campay's webhook lands (typically < 30s for MTN, < 2min for Orange). Error codes: payment_method_not_momo, order_not_payable, payment_already_processing.
         */
        post: operations["PaymentsController_initiateMomo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/campay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Campay payment status webhook */
        post: operations["CampayWebhookController_receive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/call-consumer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a masked rider → consumer call (Story 4.17)
         * @description Twilio first calls the rider; on answer, it bridges to the order's deliveryPhone. Both legs see TchopNow caller ID. Hard 3-min cap. Returns the Twilio call SID for optional client-side polling.
         */
        post: operations["VoiceProxyController_callConsumer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/twilio/voice/bridge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TwiML bridge (GET fallback for Twilio Voice) */
        get: operations["VoiceProxyController_bridgeGet"];
        put?: never;
        /** TwiML bridge (Twilio Voice webhook) */
        post: operations["VoiceProxyController_bridge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestOtpDto: {
            /**
             * @description Phone number — Cameroon local (e.g. 670000000) or international E.164 (e.g. +33695412820).
             * @example 670000000
             */
            phone: string;
        };
        VerifyOtpDto: {
            /** @example 670000000 */
            phone: string;
            /**
             * @description 6-digit OTP code
             * @example 123456
             */
            code: string;
        };
        RefreshTokenDto: {
            /** @description Refresh JWT obtained from /auth/verify-otp or a prior /auth/refresh call. */
            refreshToken: string;
        };
        UpdateUserProfileDto: {
            /**
             * @description Nom affiché.
             * @example Maman Mboué
             */
            displayName?: string;
        };
        UpsertAddressDto: {
            /** @example Maison */
            label?: string;
            /** @description Free-form description (e.g. "2ème portail bleu après le transformateur"). */
            description?: string;
            /** @example Makepe */
            quartier?: string;
            /** @description Landmark UUID (Story 2.15). */
            landmarkId?: string;
            /** @example 4.0511 */
            lat: number;
            /** @example 9.7679 */
            lng: number;
            /** @description Delivery phone. Defaults to the user's account phone at order time if unset. */
            phone?: string;
            /** @default false */
            isDefault: boolean;
        };
        CartLineDto: {
            /** @description Item UUID (must belong to the same vendor as the cart). */
            itemId: string;
            /** @example 1 */
            quantity: number;
        };
        CreateOrderDto: {
            /** @description Target vendor UUID. All cart lines must belong to it. */
            vendorId: string;
            items: components["schemas"]["CartLineDto"][];
            /** @enum {string} */
            paymentMethod: "MTN_MOMO" | "ORANGE_MONEY" | "CASH";
            /**
             * @description Note for the vendor — the only client→vendor channel. Max 120 chars.
             * @example Sans piment
             */
            noteForVendor?: string;
            /** @example 4.0511 */
            deliveryLat: number;
            /** @example 9.7679 */
            deliveryLng: number;
            /** @example Makepe */
            deliveryQuartier: string;
            /** @example Rond-Point Total Makepe */
            deliveryLandmark?: string;
            /** @example 2ème portail bleu après le transformateur */
            deliveryDescription?: string;
            /** @description Phone the rider will call if lost. E.164 or Cameroon local. */
            deliveryPhone: string;
        };
        RateOrderDto: {
            /** @example 5 */
            vendorScore: number;
            /** @example 4 */
            riderScore: number;
            comment?: string;
        };
        RefuseOrderDto: {
            /** @enum {string} */
            reason: "ITEM_OUT_OF_STOCK" | "CLOSED" | "TOO_MANY_ORDERS" | "POWER_OUTAGE" | "OTHER";
            /** @description Free-text note (required when reason=OTHER). */
            note?: string;
        };
        SubmitVendorDto: {
            /**
             * @description Nom de la cuisine.
             * @example Chez Maman Mboué
             */
            name: string;
            /**
             * @description Quartier de Douala.
             * @example Makepe
             */
            quartier: string;
            /**
             * @description Point de repère (optionnel).
             * @example En face de la pharmacie Sainte-Marie
             */
            pointOfReference?: string;
            /**
             * @description WhatsApp phone — Cameroon local or international E.164.
             * @example 670000000
             */
            whatsappPhone: string;
            /**
             * @description MTN MoMo or Orange Money phone — Cameroon local or E.164.
             * @example 670000000
             */
            momoPhone: string;
            /**
             * @description Capacité déclarée (Écran 4).
             * @example R_10_30
             * @enum {string}
             */
            declaredCapacity: "LT_10" | "R_10_30" | "GT_30";
            /**
             * @description Nom du premier plat.
             * @example Poulet DG
             */
            firstItemName: string;
            /**
             * @description Prix du premier plat en FCFA (entier, positif).
             * @example 3000
             */
            firstItemPriceXAF: number;
        };
        UpdateVendorProfileDto: {
            /** @example Chez Maman Mboué */
            name?: string;
            /** @example La meilleure cuisine de Makepe — plats du jour à partir de 1 500 FCFA. */
            description?: string;
            /** @description New MoMo number. No OTP-on-new-number confirmation in MVP — admin oversight handles fraud cases at launch. */
            momoPhone?: string;
        };
        UpsertItemDto: {
            /** @example Poulet DG */
            name: string;
            /** @example Poulet rôti, plantains, légumes du jour. */
            description?: string;
            /**
             * @description Prix entier FCFA (>= 100).
             * @example 3000
             */
            priceXAF: number;
            /** @description UUID d'une MenuCategory du même vendeur. */
            categoryId?: string;
            /**
             * @description Temps de préparation moyen (minutes). Restaurants uniquement.
             * @example 20
             */
            preparationMinutes?: number;
            /**
             * @description Ordre d'affichage. Lower = first.
             * @example 0
             */
            sortOrder?: number;
        };
        UpdateItemStockDto: {
            /**
             * @description true = Disponible, false = Épuisé.
             * @example false
             */
            isInStock: boolean;
        };
        UpsertCategoryDto: {
            /** @example Plats */
            name: string;
            /** @example 0 */
            sortOrder?: number;
        };
        UpdateAvailabilityDto: {
            /** @example true */
            isOpen: boolean;
        };
        DayHours: {
            /** @example 07:30 */
            open: string;
            /** @example 21:00 */
            close: string;
        };
        UpdateHoursDto: {
            mon?: components["schemas"]["DayHours"];
            tue?: components["schemas"]["DayHours"];
            wed?: components["schemas"]["DayHours"];
            thu?: components["schemas"]["DayHours"];
            fri?: components["schemas"]["DayHours"];
            sat?: components["schemas"]["DayHours"];
            sun?: components["schemas"]["DayHours"];
        };
        SubmitRiderDto: {
            /**
             * @description Nom complet du livreur.
             * @example Jean Mboué
             */
            name: string;
            /**
             * @description Cameroon local or international E.164.
             * @example 670000020
             */
            phone: string;
            /**
             * @example MOTO
             * @enum {string}
             */
            vehicleType: "MOTO" | "BICYCLE" | "CAR" | "ON_FOOT";
            /**
             * @description Zone de livraison préférée (quartier, secteur).
             * @example Makepe
             */
            preferredZone?: string;
            /**
             * @description Numéro de plaque (requis pour MOTO et CAR ; optionnel pour BICYCLE ; absent pour ON_FOOT). Lettres majuscules, chiffres et tirets.
             * @example LT1234
             */
            licensePlate?: string;
            /**
             * @description Cameroon local or international E.164.
             * @example 670000020
             */
            momoPhone: string;
        };
        UpdateRiderProfileDto: {
            /** @example Bonamoussadi */
            preferredZone?: string;
            momoPhone?: string;
        };
        RiderAvailabilityDto: {
            /** @example true */
            isOnline: boolean;
        };
        RiderHeartbeatDto: {
            /** @example 4.0511 */
            lat: number;
            /** @example 9.7679 */
            lng: number;
        };
        AdminLoginDto: {
            /** @example admin@chopnow.app */
            email: string;
            /**
             * @description Min 12 chars, must include uppercase, digit, and special char.
             * @example StrongPwd!2026
             */
            password: string;
        };
        AdminDecisionDto: {
            /**
             * @description Free-text reason — shown to the vendor/rider in their WhatsApp notification.
             * @example Photo de pièce d'identité illisible
             */
            reason?: string;
        };
        InitiateMomoPaymentDto: {
            /**
             * @description MTN MoMo or Orange Money number — Cameroon local or E.164.
             * @example 670000000
             */
            payerPhone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestOtpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddressesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddressesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAddressDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddressesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAddressDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddressesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_rate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_vendorList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_refuse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefuseOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VendorController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SubmitVendorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VendorController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVendorProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VendorController_updateMePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_listItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_setStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemStockDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_setPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MenuController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityController_setAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityController_setHours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHoursDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrowseController_catalogue: {
        parameters: {
            query: {
                /** @description Consumer latitude. */
                lat: number;
                /** @description Consumer longitude. */
                lng: number;
                /** @description Max distance to fetch in km. Defaults to 10 (covers Douala metro). Catalogue groups results into 3 plans (≤2km, ≤5km, >5km) regardless. */
                radiusKm?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrowseController_vendorPublic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SubmitRiderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRiderProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_setAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiderAvailabilityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_pushHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiderHeartbeatDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_markPickedUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_markDelivered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_listPendingVendors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_approveVendor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_rejectVendor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDecisionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_suspendVendor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDecisionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_unsuspendVendor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_listPendingRiders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_approveRider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                riderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_rejectRider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                riderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDecisionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_suspendRider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                riderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDecisionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminValidationController_unsuspendRider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                riderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_initiateMomo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiateMomoPaymentDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampayWebhookController_receive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VoiceProxyController_callConsumer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VoiceProxyController_bridgeGet: {
        parameters: {
            query: {
                orderId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VoiceProxyController_bridge: {
        parameters: {
            query: {
                orderId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
