/**
 * iOS PWA splash-screen table.
 *
 * iOS Safari does NOT read manifest.json's `splash_screens` field — Apple
 * requires a `<link rel="apple-touch-startup-image">` per device size and
 * orientation, matched by a `media` query that combines device-width,
 * device-height, pixel-ratio, and orientation.
 *
 * Without these, an installed PWA launches with a blank white screen for
 * ~500ms before paint (longer on 3G). With them, the user sees a branded
 * splash with the app icon centered on warm-white background — feels
 * native, not browser-y.
 *
 * The PNGs themselves are generated by `pwa-asset-generator` from the
 * 512×512 app icon. Regenerate via:
 *
 *   npx pwa-asset-generator@6 public/icons/icon-512.png public/icons/splash \
 *     --background "#FAFAF7" --opaque true --type png --quality 90 \
 *     --portrait-only false --landscape true --favicon false \
 *     --icon-only false --splash-only true \
 *     --padding "calc(50vh - 30%) calc(50vw - 30%)"
 *
 * Covers iPhone SE (2nd gen) through iPhone 15 Pro Max + all current
 * iPad sizes. Tested against Apple's HIG device matrix (2026-05).
 */
export const APPLE_SPLASH_SCREENS = [
  // iPad Pro 12.9"
  {
    deviceWidth: 1024,
    deviceHeight: 1366,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-2048-2732.png',
  },
  {
    deviceWidth: 1024,
    deviceHeight: 1366,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-2732-2048.png',
  },
  // iPad Pro 11"
  {
    deviceWidth: 834,
    deviceHeight: 1194,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-1668-2388.png',
  },
  {
    deviceWidth: 834,
    deviceHeight: 1194,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-2388-1668.png',
  },
  // iPad 10.2" / Air 3
  {
    deviceWidth: 834,
    deviceHeight: 1112,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-1668-2224.png',
  },
  {
    deviceWidth: 834,
    deviceHeight: 1112,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-2224-1668.png',
  },
  // iPad 9.7"
  {
    deviceWidth: 768,
    deviceHeight: 1024,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-1536-2048.png',
  },
  {
    deviceWidth: 768,
    deviceHeight: 1024,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-2048-1536.png',
  },
  // iPad 10th gen
  {
    deviceWidth: 810,
    deviceHeight: 1080,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-1620-2160.png',
  },
  {
    deviceWidth: 810,
    deviceHeight: 1080,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-2160-1620.png',
  },
  // iPhone 14 Pro Max / 15 Pro Max
  {
    deviceWidth: 430,
    deviceHeight: 932,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1290-2796.png',
  },
  {
    deviceWidth: 430,
    deviceHeight: 932,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2796-1290.png',
  },
  // iPhone 14 Pro / 15 Pro
  {
    deviceWidth: 393,
    deviceHeight: 852,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1179-2556.png',
  },
  {
    deviceWidth: 393,
    deviceHeight: 852,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2556-1179.png',
  },
  // iPhone 12/13/14 Pro Max + Plus
  {
    deviceWidth: 428,
    deviceHeight: 926,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1284-2778.png',
  },
  {
    deviceWidth: 428,
    deviceHeight: 926,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2778-1284.png',
  },
  // iPhone 12/13/14
  {
    deviceWidth: 390,
    deviceHeight: 844,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1170-2532.png',
  },
  {
    deviceWidth: 390,
    deviceHeight: 844,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2532-1170.png',
  },
  // iPhone X / XS / 11 Pro / 12 mini / 13 mini
  {
    deviceWidth: 375,
    deviceHeight: 812,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1125-2436.png',
  },
  {
    deviceWidth: 375,
    deviceHeight: 812,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2436-1125.png',
  },
  // iPhone XS Max / 11 Pro Max
  {
    deviceWidth: 414,
    deviceHeight: 896,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1242-2688.png',
  },
  {
    deviceWidth: 414,
    deviceHeight: 896,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2688-1242.png',
  },
  // iPhone XR / 11
  {
    deviceWidth: 414,
    deviceHeight: 896,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-828-1792.png',
  },
  {
    deviceWidth: 414,
    deviceHeight: 896,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-1792-828.png',
  },
  // iPhone 8 Plus / 7 Plus / 6S Plus (still in field on Tecno/Itel equivalent)
  {
    deviceWidth: 414,
    deviceHeight: 736,
    pixelRatio: 3,
    orientation: 'portrait',
    file: 'apple-splash-1242-2208.png',
  },
  {
    deviceWidth: 414,
    deviceHeight: 736,
    pixelRatio: 3,
    orientation: 'landscape',
    file: 'apple-splash-2208-1242.png',
  },
  // iPhone SE (2nd/3rd gen) / 8 / 7 / 6S
  {
    deviceWidth: 375,
    deviceHeight: 667,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-750-1334.png',
  },
  {
    deviceWidth: 375,
    deviceHeight: 667,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-1334-750.png',
  },
  // iPhone SE (1st gen) / 5S / 5C / 5 — covers oldest fleet
  {
    deviceWidth: 320,
    deviceHeight: 568,
    pixelRatio: 2,
    orientation: 'portrait',
    file: 'apple-splash-640-1136.png',
  },
  {
    deviceWidth: 320,
    deviceHeight: 568,
    pixelRatio: 2,
    orientation: 'landscape',
    file: 'apple-splash-1136-640.png',
  },
] as const;
